baseURL = 'https://www.aspose.com/'
languageCode = 'en-us'
title = 'Policies - Aspose'
theme = "policies"
enableRobotsTXT = true

[module]
[[module.mounts]]
 source = "assets/images"
 target = "assets/images"